@Kleios.Backend.System_HostAddress =https://localhost:7113/ 

GET {{Kleios.Backend.System_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Kleios.Backend.System_HostAddress}}/api/debug-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNmZjYzViYy0zOGJmLTQ0ZWQtOTgyNi02YzlmMDRlYTA0NTciLCJlbWFpbCI6Im1hc3RlckBrbGVpb3MuY29tIiwianRpIjoiNDBlYTQyNmQtYTg4Mi00YWQ1LTkxNTYtYjE4NWRlMjM1NTM1IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Im1hc3RlciIsInNlY3VyaXR5X3N0YW1wIjoiNzVYVkpQRTZIQVlFTkFNUzdPVldTQVJSWERSSUVOUEMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBbW1pbmlzdHJhdG9yZSIsIlBlcm1pc3Npb24iOlsiUm9sZXMuTWFuYWdlIiwiUm9sZXMuVmlldyIsIlNldHRpbmdzLk1hbmFnZSIsIlNldHRpbmdzLlZpZXciLCJVc2Vycy5NYW5hZ2UiLCJVc2Vycy5WaWV3IiwiTG9ncy5NYW5hZ2UiLCJMb2dzLlZpZXciXSwiZXhwIjoxNzQ1NTM1MDUxLCJpc3MiOiJLbGVpb3MiLCJhdWQiOiJLbGVpb3NVc2VycyJ9.lONFer8IAA9uEHnU2KRS7-NGISRJ0XbeirYAlwuV8PA
